### ISSUE TITLE
#1 Write a separate method to get Adapters for the spinners

### ISSUE THREAD

**Issue by ghost** [andela-tsolarin/Calcurren#1]
In CalculatorActivity.java, refactor line 55 - 65.

ArrayAdapter<String> currencyAdapter = getCurrencyAdapter();
currSpinner.setAdapter(currencyAdapter);
baseSpinner.setAdapter(currencyAdapter);

Write a getCurrencyAdapter() method separately

**Comment by tonerdo** [comment]
All done in both CalculatorActivity and TopCurrenciesActivity
