### ISSUE TITLE
#2 Your CalculatorOperations Class is too tied to the CalculatorActivity

### ISSUE THREAD

**Issue by ghost** [andela-tsolarin/Calcurren#2]
You are manipulating the CalculatorActivity Display Views from the CalculatorOperations class. Please loosen this tie. Apply the views from CalculatorActivity and let CalculatorOperations be sufficiently independent.

Please refactor this.

**Comment by tonerdo** [comment]
The CalculatorOperations class has been made sufficiently independent of the CalculatorActivity class
